
CREATE TABLE IF NOT EXISTS Sun_weather
(
    id INTEGER PRIMARY KEY,
    DATE TIMESTAMP,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    WEEK INTEGER,
    HOUR INTEGER,
    Sunrise FLOAT,
    Sunset FLOAT
);
